version: "3.9"

services:
  db:
    image: postgres:15
    container_name: avito_db
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
      # если есть SQL-скрипты инициализации — положи их в db/init/
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build: .
    container_name: avito_app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      NOTIFY_DB_URL: ${NOTIFY_DB_URL}
      TOKENS_PATH: /app/runtime/tokens.json
      PORT: ${APP_PORT:-8000}
    volumes:
      - ./runtime:/app/runtime        # R/W хранилище для tokens.json
    ports:
      - "${APP_PORT:-8000}:8000"

volumes:
  pg_data:
